<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */


/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://wordpress.org/support/article/editing-wp-config-php/
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'bedrock' );

/** MySQL database username */
define( 'DB_USER', 'root' );

/** MySQL database password */
define( 'DB_PASSWORD', 'mysql' );

/** MySQL hostname */
define( 'DB_HOST', 'localhost' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define( 'AUTH_KEY',         'Wl7kr=CM]S>Wa}6]E*CLPN(?kFi+[Yh.Vw[E;EN8+=eH<NtBZo*r#{<Q!vbS*VUu' );
define( 'SECURE_AUTH_KEY',  '=<Dr/9C3>Ng.t|runD.vCY)@1|u@FbFX=BU*F>Bp-*JTaM_6Wor(:^<H[OI%g%3;' );
define( 'LOGGED_IN_KEY',    'Qo}{^i=w1ZX%7^+?UU<JS@O6*mT83!:2{-lv*G)Hn!;f{_`F1xQo6mE$8rN<##WG' );
define( 'NONCE_KEY',        'z`1yAD@AoZdVbZhgXA=@y7E+n#p@z@)xc%g4iCz=kxhxGKT97bxppWZT[vp|l;_(' );
define( 'AUTH_SALT',        '|QSI6qMs,k(<oLim};s*ryeO]&9Y{i%S8Z6N8.ygU6P2zP^7I=+&n]^,(M<m>wqy' );
define( 'SECURE_AUTH_SALT', 'nbD-}zjzVM4<^R.O,Vu-yORH-[@}]WWZ0GK{8f7#6s#$F2Pd(`O4af}^ZTYw!f$7' );
define( 'LOGGED_IN_SALT',   'ayyE$Ctm(*x/_/o(.u-<JV8wWzE{dF_({KBxF&#3xBba$$k*hIt`C4,d,vu(FA@}' );
define( 'NONCE_SALT',       'QawLo`!rY$1x7c!bPTOgIN#eaDhi@{L%J^k/$F;vM6HI^dPJ>G.I*,7xN$h4**gH' );


/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the documentation.
 *
 * @link https://wordpress.org/support/article/debugging-in-wordpress/
 */
define( 'WP_DEBUG', false );

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
# Generate your keys here: https://roots.io/salts.html